[package]
name = "esp32c3_ota_experiment"
version = "0.1.0"
authors = ["bjoernQ <bjoern.quentin@mobile-j.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp32c3-hal = "0.2.0"
riscv-rt = { version = "0.9", optional = true }

esp-wifi = { git = "https://github.com/esp-rs/esp-wifi.git", features = ["esp32c3", "embedded-svc", "wifi"] }
smoltcp = { version = "0.8.0", default-features=false, features = ["proto-igmp", "proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }
embedded-svc = { version = "0.22.1", default-features = false}
log = "0.4.16"
nb = "1.0.0"
embedded-hal = "0.2"
esp-println = {version="0.3.1", features = [ "esp32c3", "uart"] }
esp-backtrace = {version="0.2.0", features = [ "esp32c3", "print-uart", "panic-handler"] }
esp-storage = { version = "0.1.0", features = ["esp32c3"] }
embedded-storage = "0.3.0"
crc = "3.0.0"

[features]
default = ["rt"]
rt = ["riscv-rt"]
