[package]
name = "partitions-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.3.1"
proc-macro-error = "1.0.4"
proc-macro2      = "1.0.52"
quote            = "1.0.26"
litrs            = "0.4.0"

esp-idf-part = "0.3.0"
